### ISSUE TITLE
Duvidas sobre utilização

### ISSUE THREAD

**Issue by waltenne** [faelvinicius/non-compliant-awsconfig#1]
Boa tarde! Tudo joia?

Sobre os Script a macro {$ACCOUNT}, devo criar uma macro com o nome do profile que está no .aws/config?

Se uma conta tiver serviços em várias regiões, como ficaria?

**Comment by faelvinicius** [comment]
Então. Seria isso mesmo. Eu criei as macros nos hosts e coloquei o nome do profile que criei no .aws/config.
A principio fiz eu fiz só para uma região, acho que pra pegar várias regiões seria um pouco mais complicado, mas acredito que tem como fazer. Vou testar isso e atualizo aqui.

Eu vou atualizar o readme com o passo a passo mais detalhado da configuração. Mas a ideia é essa, criar as Macros para account.

**Comment by faelvinicius** [comment]
> Boa tarde! Tudo joia?
> 
> Sobre os Script a macro {$ACCOUNT}, devo criar uma macro com o nome do profile que está no .aws/config?
> 
> Se uma conta tiver serviços em várias regiões, como ficaria?

Tudo joia e vc?
Então. Seria isso mesmo. Eu criei as macros nos hosts e coloquei o nome do profile que criei no .aws/config.
A principio fiz eu fiz só para uma região, acho que pra pegar várias regiões seria um pouco mais complicado, mas acredito que tem como fazer. Vou testar isso e atualizo aqui.

Eu vou atualizar o readme com o passo a passo mais detalhado da configuração. Mas a ideia é essa, criar as Macros para account.

**Comment by waltenne** [comment]
Obrigado, comecei a entender o funcionamento, porém estou com dificuldades para realizar alguns ajustes

Sabe se existe a possibilidade de filtrar apenas instancias com lifecycle normal e spot separadas na mesma região?

**Comment by waltenne** [comment]
Obrigado pelo seu retorno!

Devido algumas dificuldades para uso direto do aws cli, achei uma forma de fazer essas tratativas via python pelo boto3, estou desenhando o esboço de todas as necessidades e brincando, assim que estiver legal irei compartilhar no meu github.

Até o momento consegui no script passando 3 parâmetros fazer a consulta 
 * Por Conta
 * Por Região
 * Por Lifecycle (Ondemand ou Spot)

Devolvendo algumas informações básicas das instancias, nome, estado, regiao, tipo de instancia e ip publico e privado, agora, vou implementar para retornar dados dos bancos de dados e também de instancias reservadas
